### ISSUE TITLE
Add optional parameter to filter polygons larger than x m²

### ISSUE THREAD

**Issue by iboates** [JakobMiksch/osm-feature-info#9]
One thing I found annoying on the OSM website was that whenever you click, you will get the entire hierarchy of administrative polygons, which you might sometimes want, but often times I think people are zoomed in really far and are looking for info on buildings, streets, or other POIs

I suggest adding an optional parameter to the query which will not return polygons over a certain area, so that with a large value like 100 km², you will effectively exclude all the administrative boundaries or other large, encompassing-features. I realize it's not totally robust but I think it would be a nice convenience feature on the interface.

Thoughts?

**Comment by JakobMiksch** [comment]
sounds good, theoretically one can compute the area of all polygons
but maybe it is already enough to check if the polygon's BBOX is within a specific range ...

**Comment by JakobMiksch** [comment]
not needed because the current osm website does not do it as well and currently we want to have feature parity with the osm website
